# -*- coding: utf-8 -*-
"""Recommender System Group 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwkISkbPn1kPPsmae8aNXQlY-Mm8xWOi

scikit-surprise: library for collaborative filtering and recommendation models.

pandas and numpy: for data manipulation and numerical operations.

matplotlib and seaborn: for data visualization.

scikit-learn: for machine learning tools, including TF-IDF and train-test splitting.
"""

!pip install scikit-surprise
!pip install pandas numpy==1.26.4 matplotlib seaborn scikit-learn

"""json, pandas, numpy: for data handling and processing

seaborn, matplotlib: for data visualization

sklearn.model_selection.train_test_split: for splitting data into train/test sets

surprise: for collaborative filtering using SVD

TfidfVectorizer, linear_kernel: for content-based text analysis and similarity calculations
"""

import json
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from collections import defaultdict
from sklearn.model_selection import train_test_split
from surprise import Dataset
from surprise import Reader
from surprise import SVD
from surprise.model_selection import train_test_split as surprise_split
from surprise import accuracy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

"""In this step, We use the wget command to download a dataset from an online source into my Google Colab environment."""

!wget http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Clothing_Shoes_and_Jewelry_5.json.gz

"""In this step, We extract the downloaded dataset file so it can be used for analysis."""

!gunzip reviews_Clothing_Shoes_and_Jewelry_5.json.gz

"""In this step, We read the JSON file and convert it into a pandas DataFrame.

We open the file and read it line by line (each line is one review).

We limit the data to 200,000 records to keep it manageable.

Each line is converted from JSON into a Python dictionary.

We extract useful fields like user ID, item ID, rating, review text, and timestamp.

The data is stored in a list and then converted into a DataFrame for analysis.

Finally, We use df.head() to preview the dataset.
"""

data = []
with open("reviews_Clothing_Shoes_and_Jewelry_5.json","r") as f:
    for i,line in enumerate(f):
        if i > 200000:
            break

        review = json.loads(line)
        data.append({
            "user_id": review["reviewerID"],
            "item_id": review["asin"],
            "rating": review["overall"],
            "review": review.get("reviewText",""),
            "timestamp": review["unixReviewTime"]
        })

df = pd.DataFrame(data)
df.head()

"""In this step, We check some basic information about the dataset:

Interactions: total number of reviews (rows in the dataset)

Users: number of unique users who gave reviews

Items: number of unique products reviewed
"""

print("Interactions:",len(df))
print("Users:",df['user_id'].nunique())
print("Items:",df['item_id'].nunique())

sns.countplot(x='rating',data=df)
plt.title("Rating Distribution")
plt.show()

"""In this step, We filter the dataset to keep only meaningful data:

We count how many times each user and item appears.

We keep only users and items with at least 5 interactions.

This removes very rare users/items that may add noise.

The dataset is then filtered based on these conditions.

Finally, We print the new dataset shape to see the updated size.
"""

user_counts = df['user_id'].value_counts()
item_counts = df['item_id'].value_counts()

valid_users = user_counts[user_counts >= 5].index
valid_items = item_counts[item_counts >= 5].index

df = df[df['user_id'].isin(valid_users)]
df = df[df['item_id'].isin(valid_items)]

print("Balanced dataset:",df.shape)

sample_df = df.sample(500)
pivot = sample_df.pivot_table(
    index='user_id',
    columns='item_id',
    values='rating'
)
plt.figure()
sns.heatmap(pivot.fillna(0), cmap='viridis')
plt.title("User-Item Interaction Heatmap")
plt.show()

"""In this step, I split the dataset into training and testing sets:

1. 80% of the data is used for training the model

2. 20% is used for testing its performance

3. random_state=42 ensures the split is reproducible

This helps evaluate how well the model performs on unseen data.
"""

train_df,test_df = train_test_split(df,test_size=0.2,random_state=42)

"""Building a Recommendation Model with SVD

In this step, We use the Surprise library to train a collaborative filtering model:

1. Reader defines the rating scale (1 to 5).

2. Dataset.load_from_df converts the DataFrame into Surprise’s dataset format.

3. We split the data into train and test sets (trainset and testset).

4. SVD() creates a matrix factorization model.

5. We train the model with svd_model.fit(trainset).

6. The model predicts ratings for the test set.

7. accuracy.rmse(predictions) computes the root mean squared error, showing how accurate the predictions are.
"""

reader = Reader(rating_scale=(1,5))
data = Dataset.load_from_df(df[['user_id','item_id','rating']],reader)
trainset,testset = surprise_split(data,test_size=0.2)
svd_model = SVD()
svd_model.fit(trainset)
predictions = svd_model.test(testset)
accuracy.rmse(predictions)

"""We define a function to recommend top-N items for a given user using our trained SVD model:

1. We get all unique items from the dataset.

2. For each item, we predict the rating the user would give using the trained SVD model.

3. We sort the items by predicted rating in descending order.

4. Finally, we return the top-N items as recommendations for that user.
"""

def recommend_cf(user_id,n=10):
    items = df['item_id'].unique()
    scores = []
    for item in items:
        pred = svd_model.predict(user_id,item)
        scores.append((item,pred.est))
    scores.sort(key=lambda x:x[1],reverse=True)
    return scores[:n]

"""We process the review text to use in a content-based recommendation model:

1. We fill missing review texts with empty strings to avoid errors.

2. TfidfVectorizer converts text into numerical features based on term frequency–inverse document frequency (TF-IDF).

3. Parameters:

    stop_words='english': remove common English words

    max_features=5000: keep only the top 5000 words

    min_df=5, max_df=0.8: include words that appear in at least 5 reviews but in no more than 80% of all reviews

4. tfidf_matrix stores the numerical representation of all reviews, ready for content-based analysis.
"""

item_df = df.groupby('item_id')['review'].apply(lambda x: ' '.join(x)).reset_index()
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000,
    min_df=5,
    max_df=0.8
)

tfidf_matrix = tfidf.fit_transform(item_df['review'])
print(f"\nTF-IDF Matrix Shape: {tfidf_matrix.shape}")
print(f"item_df shape: {item_df.shape}")
print(f"Number of unique items: {len(item_df)}")

"""We define a function to compute a content similarity score for a given item:

1. We use linear_kernel to calculate cosine similarity between the given item and all other items based on TF-IDF features.

2. The function computes how similar the item is to others in terms of review content.

3. We return the average similarity score, which can be used to rank items for content-based recommendations.
"""

def content_score(item_index):
    sim_scores = linear_kernel(
        tfidf_matrix[item_index:item_index+1],
        tfidf_matrix
    ).flatten()
    return sim_scores

"""e define a function to estimate the confidence of a predicted rating:

1. Ratings closer to 1 or 5 are considered more confident.

2. Ratings near 3 are less confident.

3. The function returns a normalized confidence score between 0 and 1.
"""

def prediction_confidence(pred_rating):
    confidence = abs(pred_rating - 3) / 2
    return confidence

"""We define a function to recommend top-N items by combining collaborative filtering and content-based methods:

1. For each item, we compute: collaborative filtering prediction, content similarity, and prediction confidence.

2. We combine them into a hybrid score using weighted averages (0.6 CF, 0.3 content, 0.1 confidence).

3. Items are sorted by this score, and we return the top-N recommendations for the user.
"""

def hybrid_recommend(user_id, top_n=10):
    items = item_df['item_id'].values
    results = []
    for item in items:
        cf_pred = svd_model.predict(user_id, item).est
        idx = item_df[item_df['item_id'] == item].index[0]
        content_sim = content_score(idx).mean()
        confidence = prediction_confidence(cf_pred)
        hybrid_score = (
            0.6 * cf_pred +
            0.3 * content_sim +
            0.1 * confidence
        )
        results.append((item, hybrid_score, confidence))
    results.sort(key=lambda x: x[1], reverse=True)
    return results[:top_n]

"""We define a function to recommend items only when the model is confident:

1. We first generate top-20 hybrid recommendations for the user.

2. For each item, we check the confidence score.

3. Only items with confidence above the threshold are included.

4. Finally, we return the top-10 confident recommendations.

This ensures that we avoid recommending items when the model is uncertain, improving reliability.
"""

def recommend_with_abstention(user_id, threshold=0.4):
    recs = hybrid_recommend(user_id, top_n=20)
    final_recs = []
    for item,score,conf in recs:
        if conf >= threshold:
            final_recs.append((item,score))
    return final_recs[:10]

"""We define a function to recommend items similar to a given item based on review content:

1. We calculate cosine similarity between the selected item and all other items using their TF-IDF features.

2. We sort items by similarity and select the top-N most similar items.

3. The function returns the item_id and review text of the recommended items.
"""

def recommend_content(item_id, top_n=10):
    idx = item_df[item_df['item_id'] == item_id].index[0]
    cosine_sim = linear_kernel(
        tfidf_matrix[idx:idx+1],
        tfidf_matrix
    ).flatten()
    similar_indices = cosine_sim.argsort()[-top_n-1:-1][::-1]
    return item_df.iloc[similar_indices]['item_id']

sample_user = df['user_id'].iloc[0]
items = df['item_id'].unique()[:20]
cf_scores = []
content_scores = []
confidence_scores = []
for idx, item in enumerate(items):
    cf = svd_model.predict(sample_user, item).est
    content = content_score(idx)
    conf = prediction_confidence(cf)

    cf_scores.append(cf)
    content_scores.append(content)
    confidence_scores.append(conf)
plt.figure()
plt.plot(cf_scores, label="CF Score")
plt.plot(content_scores, label="Content Score")
plt.plot(confidence_scores, label="Confidence")
plt.title("Hybrid Recommendation Components")
plt.xlabel("Items")
plt.ylabel("Score")
plt.legend()
plt.show()

"""we are grouping the data by each item and then looking at two things: the average rating for each item, and how many times each item was rated. This helps you see not only which items are rated highly, but also how many people rated them, so you know how reliable those ratings are."""

item_stats = df.groupby('item_id')['rating'].agg(['mean', 'count'])

item_stats['count_norm'] = item_stats['count'] / item_stats['count'].max()
item_stats['popularity_score'] = (
    0.7 * item_stats['mean'] +
    0.3 * item_stats['count_norm']
)

"""This function recommends items to a user depending on how much information you have about them.

If the user is completely new and hasn’t reviewed anything, it simply recommends the most popular items overall.

If the user has written some reviews, it does a mix of two things:
it looks for items that are similar to what the user liked before (using text similarity), and it also considers how popular those items are. It then combines these two scores, ranks the items, and returns the top recommendations.
"""

def cold_start_user_recommend(user_reviews, top_n=10):
    # Case 1: completely new user
    if len(user_reviews) == 0:
        top_items = item_stats.sort_values(
            'popularity_score', ascending=False
        ).head(top_n)
        return top_items.index.tolist()

    # Case 2: user has some reviews → hybrid approach
    user_profile = tfidf.transform(user_reviews)
    sim_scores = linear_kernel(user_profile, tfidf_matrix).flatten()
    sim_scores = sim_scores / sim_scores.max()
    results = []
    for idx, item in enumerate(item_df['item_id']):
        content_sim = sim_scores[idx]
        pop_score = item_stats.loc[item, 'popularity_score'] \
            if item in item_stats.index else 0
        final_score = (
            0.6 * content_sim +
            0.4 * pop_score
        )

        results.append((item, final_score))
    results.sort(key=lambda x: x[1], reverse=True)
    return [item for item, _ in results[:top_n]]

"""We define a function to calculate Precision at K for evaluating our recommendation model:

1. We sort predictions by the estimated rating (pred.est) in descending order.

2. We select the top-K predicted items.

3. An item is considered relevant if its true rating (pred.r_ui) is 4 or higher.

4. Precision@K is the fraction of relevant items in the top-K recommendations.

This metric helps us measure how accurate the model’s top recommendations are for users.
"""

def precision_at_k(predictions, k=10, threshold=4):
    user_preds = get_user_predictions(predictions)
    precisions = []
    for uid, user_ratings in user_preds.items():
        user_ratings.sort(key=lambda x: x.est, reverse=True)
        top_k = user_ratings[:k]
        relevant = sum((pred.r_ui >= threshold) for pred in top_k)
        precisions.append(relevant / k)
    return np.mean(precisions)

"""We define a function to calculate Recall at K for evaluating our recommendation model:

1. We sort predictions by estimated rating (pred.est) in descending order.

2. We select the top-K predicted items.

3. An item is relevant if its true rating (pred.r_ui) is 4 or higher.

4. Recall@K is the fraction of all relevant items that appear in the top-K recommendations.

This metric helps us measure how well the model captures all relevant items in its top recommendations.
"""

def recall_at_k(predictions, k=10, threshold=4):
    user_preds = get_user_predictions(predictions)
    recalls = []
    for uid, user_ratings in user_preds.items():
        user_ratings.sort(key=lambda x: x.est, reverse=True)
        top_k = user_ratings[:k]
        relevant = sum((pred.r_ui >= threshold) for pred in top_k)
        total_relevant = sum((pred.r_ui >= threshold) for pred in user_ratings)
        if total_relevant > 0:
            recalls.append(relevant / total_relevant)
    return np.mean(recalls)

"""We define a function to calculate Normalized Discounted Cumulative Gain (NDCG) at K, which evaluates the quality of ranked recommendations:

1. We sort predictions by estimated rating (pred.est) in descending order.

2. DCG (Discounted Cumulative Gain) sums the relevance of top-K items, giving higher-ranked items more weight.

3. IDCG is the ideal DCG if items were perfectly ranked by true ratings.

4. NDCG@K is the ratio of DCG to IDCG, giving a score between 0 and 1.

This metric helps us assess how well the ranking of our recommendations aligns with actual user preferences.
"""

def ndcg_at_k(predictions, k=10):
    user_preds = get_user_predictions(predictions)
    ndcgs = []
    for uid, user_ratings in user_preds.items():
        user_ratings.sort(key=lambda x: x.est, reverse=True)
        dcg = 0
        for i, pred in enumerate(user_ratings[:k]):
            rel = pred.r_ui
            dcg += (2**rel - 1) / np.log2(i + 2)
        ideal = sorted([pred.r_ui for pred in user_ratings], reverse=True)[:k]
        idcg = 0
        for i, rel in enumerate(ideal):
            idcg += (2**rel - 1) / np.log2(i + 2)
        if idcg > 0:
            ndcgs.append(dcg / idcg)
    return np.mean(ndcgs)

"""We define a function to calculate MAP at K, which evaluates the quality of ranked recommendations:

1. We sort predictions by estimated rating (pred.est) in descending order.

2. For the top-K predicted items, we track “hits” where the true rating (pred.r_ui) is 4 or higher.

3. Each hit contributes precision at that rank to the score.

4. MAP@K is the average precision across all hits, normalized so it is between 0 and 1.

This metric helps us measure how precise the model is at ranking relevant items at the top of the recommendation list.
"""

def map_at_k(predictions, k=10, threshold=4):
    user_preds = get_user_predictions(predictions)
    maps = []
    for uid, user_ratings in user_preds.items():
        user_ratings.sort(key=lambda x: x.est, reverse=True)
        score = 0
        hits = 0
        for i, pred in enumerate(user_ratings[:k]):
            if pred.r_ui >= threshold:
                hits += 1
                score += hits / (i + 1)
        if hits > 0:
            maps.append(score / hits)
    return np.mean(maps)

"""The get_user_predictions function organizes predictions by user ID using a defaultdict, grouping all predictions for each user together."""

def get_user_predictions(predictions):
    """Helper function to organize predictions by user ID"""
    user_preds = defaultdict(list)
    for pred in predictions:
        user_preds[pred.uid].append(pred)
    return user_preds

"""We calculate and print key evaluation metrics for the top-10 recommendations:

Precision@10: fraction of relevant items in the top-10 recommendations.

Recall@10: fraction of all relevant items captured in the top-10.

NDCG@10: measures how well the ranking of recommendations matches actual user preferences.

MAP@10: average precision across all relevant items in the top-10 recommendations.
"""

p = precision_at_k(predictions, 10)
r = recall_at_k(predictions, 10)
n = ndcg_at_k(predictions, 10)
m = map_at_k(predictions, 10)

print("Precision@10:", p)
print("Recall@10:", r)
print("NDCG@10:", n)
print("MAP@10:", m)

metrics = {
    "Precision@10": p,
    "Recall@10": r,
    "NDCG@10": n,
    "MAP@10": m
}
plt.figure()
plt.bar(metrics.keys(), metrics.values())
plt.title("Evaluation Metrics")
plt.xlabel("Metrics")
plt.ylabel("Score")
plt.show()

"""We generate and display recommendations for a sample user/item using three different methods:

1. Collaborative Filtering: recommends items based on similar users’ preferences.

2. Content-Based: recommends items similar in content to a given item (here, item index 10).

3. Hybrid: combines both collaborative filtering and content-based scores, along with confidence, for more balanced recommendations.

This helps us compare how each approach performs for the same user/item.
"""

print("Collaborative Filtering")
print(recommend_cf(df['user_id'].iloc[0]))
print("\nContent Based")
if len(item_df) > 0:
    item_id = item_df['item_id'].iloc[0]
    print(f"Showing recommendations for item_id: {item_id}")
    print(recommend_content(item_id))
else:
    print("No items available for content-based recommendations")
print("\nHybrid")
print(hybrid_recommend(df['user_id'].iloc[0], 10))

"""GENERATIVE AI ANALYSIS

 We employed conventional recommendation techniques, such as content-based and collaborative filtering. These approaches, however, have trouble with scant data and new users. Recommendations are improved by the ability of generative AI models, such as VAEs and GANs, to learn deeper patterns and even create novel interactions. Our system would become more precise and scalable if we included them.

Generative AI (GANs & VAEs) can enhance recommender systems.

VAEs:
- Learn latent user-item representations
- Handle sparsity better than SVD

GANs:
- Generate synthetic interactions
- Improve cold-start and diversity

Comparison:
Traditional (SVD, TF-IDF):
- Simpler, interpretable
- Struggle with sparse data

Generative:
- Capture deeper patterns
- Better personalization

Conclusion:
Integrating VAEs or GANs would improve performance, especially for cold-start and scalability.
"""